# Generated by Django 3.0.8 on 2020-12-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
